In [1]:
import sqlite3
from google.colab import drive 
drive.mount('/content/OrangeOpen')

Mounted at /content/OrangeOpen

***Connecter la base***

In [2]:
conn = sqlite3.connect('OrangeOpen/MyDrive/Project Orange Open/BDD/my_db/my_db.db')

if conn is not None:
  print("database connected.")
else:
  print("Error! cannot create the database connection.")

database connected.

***Liste des tables***

In [3]:
sql_query = """SELECT name FROM sqlite_master  
  WHERE type='table';"""
cursor = conn.cursor()
cursor.execute(sql_query)
print(cursor.fetchall())
conn.commit()

[('category',), ('Tab_Reiteration_ND',), ('employees',)]

***Cr√©ation d'une table***

In [ ]:
sql_creation_table = """ CREATE TABLE Tab_Reiteration_ND (
                                        Lib_Equipe TEXT NOT NULL,
                                        Datation DATE NOT NULL,
                                        CUID TEXT NOT NULL,
                                        Offre TEXT NOT NULL,
                                        Tendance TEXT NOT NULL,
                                        TypeActivite TEXT NOT NULL,
                                        NumeroDossier TEXT NOT NULL,
                                        exploitables FLOAT NOT NULL,
                                        Appels1Min FLOAT NOT NULL,
                                        Reit1h FLOAT NOT NULL,
                                        Reit1J FLOAT NOT NULL,
                                        Reit7J FLOAT NOT NULL,
                                        NbreReiteration FLOAT NOT NULL,
                                        Flux TEXT NOT NULL,
                                        Sous_Flux TEXT NOT NULL
                                    );
                                    """
cursor.execute(sql_creation_table)

OperationalError: ignored

***Suppression d'une table***

In [5]:
sql_creation_table = """ DROP TABLE employees;"""
cursor.execute(sql_creation_table)

DatabaseError: ignored

In [ ]:
cursor = conn.cursor()
cursor.execute('Delete from Tab_Reiteration_ND')
print(cursor.fetchall())

[]